version: 2

sources:
  - name: raw
    database: lewagon-486409
    schema: gz_raw_data
    loader: bigquery
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
         - name: date_date
           description: date of purchase
         - name: orders_id
         - name: products_id
         - name: revenue
         - name: quantity
        tests:
          - unique:
             column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: "Produits"
        columns:
         - name: products_id
           description: prix du produit
           tests:
             - unique
             - not_null
         - name: purchse_price
           description: coût d'achat
           tests:
             - not_null
      - name: ship
        identifier: raw_gz_ship
        description: "Expéditions"
        columns:
         - name: orders_id
           description: date of purchase
           tests:
             - unique
             - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: "Ads adwords"
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
            tests:
              - not_null
      - name: bing
        identifier: raw_gz_bing
        description: "source bing"
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
            tests:
              - not_null
      - name: criteo
        identifier: raw_gz_criteo
        description: "source bing"
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
            tests:
              - not_null
      - name: facebook
        identifier: raw_gz_facebook
        description: "source bing"
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
            tests:
              - not_null